// Generated by https://quicktype.io

export interface IProyects {
  idposts: number;
  title: string;
  description: string;
  img: string;
}

// Generated by https://quicktype.io

export interface IProyectIndividual {
  idposts: number;
  title: string;
  description: string;
  img: string;
}
