// Generated by https://quicktype.io

export interface IProyects {
  idposts: string;
  title: string;
  description: string;
  img: string;
  materials: null;
  stepbystep: string;
  message?: string;
}
